name: Release Desktop Beta - Linux ARM64

on:
  release:
    types: [published] # Publicação de release triggers the build

# Garante que apenas um workflow idêntico rode ao mesmo tempo, cancelando runs antigas
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# Permissões padrão
permissions: read-all

jobs:
  test:
    name: Code quality check
    runs-on: ubuntu-latest # Apenas em Ubuntu para verificação
    steps:
      - name: Checkout base
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  version:
    name: Determine version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      is_pr_build: ${{ steps.set_version.outputs.is_pr_build }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set version
        id: set_version
        run: |
          base_version=$(node -p "require('./apps/desktop/package.json').version")
          version="${{ github.event.release.tag_name }}"
          version="${version#v}"
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "📦 Release Version: ${version}"

      - name: Version Summary
        run: |
          echo "🚦 Release Version: ${{ steps.set_version.outputs.version }}"

  build:
    needs: [version, test]
    name: Build Desktop App - Linux ARM64
    runs-on: ubuntu-latest # Runner x64, mas usamos cross-compilation para arm64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install deps
        run: pnpm install --node-linker=hoisted

      - name: Install deps on Desktop
        run: npm run install-isolated --prefix=./apps/desktop

      - name: Set package version
        run: npm run workflow:set-desktop-version ${{ needs.version.outputs.version }} beta

      # Build apenas para Linux arm64 (usando flag --arm64; ajuste se o seu script não aceitar args)
      - name: Build artifact on Linux ARM64
        run: npm run desktop:build -- --arm64 --linux
        env:
          APP_URL: http://localhost:3015
          DATABASE_URL: 'postgresql://postgres@localhost:5432/postgres'
          KEY_VAULTS_SECRET: 'oLXWIiR/AKF+rWaqy9lHkrYgzpATbW3CtJp3UfkVgpE='
          NEXT_PUBLIC_DESKTOP_PROJECT_ID: ${{ secrets.UMAMI_BETA_DESKTOP_PROJECT_ID }}
          NEXT_PUBLIC_DESKTOP_UMAMI_BASE_URL: ${{ secrets.UMAMI_BETA_DESKTOP_BASE_URL }}

      # Upload do artefato (apenas arquivos relevantes para Linux arm64)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-linux-arm64
          path: |
            apps/desktop/release/latest*
            apps/desktop/release/*.arm64.AppImage  # Ajuste se o nome do arquivo for diferente
            apps/desktop/release/*.zip*  # Caso gere zip para arm64
          retention-days: 5

  publish-release:
    needs: [build, version]
    name: Publish Beta Release - Linux ARM64
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissão para upload de assets no release
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          pattern: release-*
          merge-multiple: true

      - name: List artifacts
        run: ls -R release

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            release/latest*
            release/*.arm64.AppImage
            release/*.zip*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
